<?php
/**
 * TrailZone theme setup.
 *
 * Set up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which
 * runs before the init hook. The init hook is too late for some features, such
 * as indicating support post thumbnails.
 *
 * @package WordPress
 * @subpackage TrailZone
 * @since TrailZone Theme 1.0
 */

/**
 * Add support for featured images.
 *
 * @since TrailZone Theme 1.0
 */
add_theme_support( 'post-thumbnails' );

/**
 * Add suport for autogenerated <title> tag
 *
 * @since TrailZone Theme 1.0
 */
add_action( 'after_setup_theme', 'trailzone_support_title_tag' );

function trailzone_support_title_tag() {
	add_theme_support( 'title-tag' );
}